// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_UltraBase","status":true,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"SRD_HUDMakerUltra","status":true,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"false","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"125","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}},
{"name":"GALV_CharacterFramesMZ","status":true,"description":"Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"%"}},
{"name":"GALV_DiagonalMovementMZ","status":true,"description":"(v.1.2) Enables player to move diagonally and characters can use diagonal charset.","parameters":{"dMouse":"true","dCharset":"true","dSpeed":"71.42","blockDiag":"false"}},
{"name":"GALV_LayerGraphics","status":true,"description":"(v.2.0) Create graphic layers for parallax mapping, fog, etc. View the 'Help' document for plugin commands and info.","parameters":{"Tile Size":"48"}},
{"name":"DestinationSprite","status":true,"description":"v1.0.0 - With this plugin you can change the destination place sprite of the mouse\\touch input.\r\n<DestinationSprite>","parameters":{"Sprite Figure":"Square","Custom Image":"image","Animation mode":"Blink","Fade speed":"12","Sprite Size":"48","Sprite Color":"#ffffff","Sprite Opacity":"120","Sprite Blend":"1"}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}}
];
